### ISSUE TITLE
Todo example not working

### ISSUE THREAD

**Issue by mpdairy** [rbarreiro/idrisjs#11]
I have Idris `1.3.2`. `ex0` and `ex1` work for me, but I was unable to get the `todo` example to work. It compiles and loads, but after I type in a todo task and hit enter, the task shows up with an `x` button, but the button doesn't delete it and I can't enter any more todo items (hitting enter in the text box does nothing). There are no errors in the console. I was trying to debug it by throwing some `consoleLog` statements in the `pageLoop`, but that gave me a weird compilation error, specifically:

```
                             Specifically:
                                     Type mismatch between
                                             DomRef a f g x
                                     and
                                             DomRef Nat TodoState TodoAction n
```

Also, I couldn't get the `game` example to compile:
```
idris: Erasure/getArity: definition not found for Data.Tree.Empty
CallStack (from HasCallStack):
  error, called at src/Idris/Erasure.hs:605:20 in idris-1.3.2-H43oTI1BNEN3lkGNxFuB7Z:Idris.Erasure
```

Your lib looks pretty cool and I'd like to actually use it for a little project if I can at least get the elm-like todo list example working.

**Comment by rbarreiro** [comment]
I'm currently short on time, it will take me a few weeks to check it, sorry and thanks for the feedback.

**Comment by rbarreiro** [comment]
did you added the Console m constraint to use the consoleLog?
pageLoop : (Dom m, Console m) => 
page : (Dom m, Console m) =>

**Comment by rbarreiro** [comment]
fixed on master

**Comment by mpdairy** [comment]
Thanks for fixing this!
