### ISSUE TITLE
Purely UI callbacks that don't generate events

### ISSUE THREAD

**Issue by gergoerdi** [rbarreiro/idrisjs#12]
Sometimes you need to install listeners just to change the internal state of UI components.

For example, [in this code](https://github.com/gergoerdi/codenames/blob/9107282d8049ccd3407438ad5522e7fdf602233d/src/Codenames/Versus/Web.idr#L44) I'd like to make an input box that selects its whole contents on focus, because the user will always want to replace the contents wholesale. According to [this StackOverflow answer](https://stackoverflow.com/a/480756/477476) this requres installing `onfocus` and `onmouseup` handlers; however, these handlers shouldn't generate an event as far as `idrisjs` is concerned (i.e. there's no value to return from `getInput`).

Can we add this kind of "silent", or "UI-only" event listeners?

**Comment by rbarreiro** [comment]
I think it should no be too hard to it. You can check https://github.com/rbarreiro/idrisjs/blob/master/Js/Html.idr. You can create another module like this with some extra nodes or attributes that you need.  Please let me know how it goes.

**Comment by rbarreiro** [comment]
What you want to do is probably possible with stringAttribute.

**Comment by gergoerdi** [comment]
[Indeed](https://github.com/gergoerdi/codenames/commit/1dcb6b88bf4dedbf81676b720ca9faa22fa0b260#diff-192fc49813d507d0fc8e2841944e1513R27). I didn't realize that `stringAttribute` is the ultimate escape hatch for arbitrary attribute values including callbacks.
