### ISSUE TITLE
Better representation of `LCon`

### ISSUE THREAD

**Issue by be5invis** [rbarreiro/idrisjs#3]
Currently _idrisjs_ uses an array to represent data values and use array indexing as projection. However given that `LCon` **really** has a name field, and there is a `LConstructor` declaration, could we generate real JS “classes” matching the name and arity of `LCon`? The final classes may be:

```js
function Nil_0() { }
function Cons_2($0, $1) { this.$0 = $0; this.$1 = $1 }
... new Cons_2(..., ...) // LCon
... a.$1 // LProj
```

**Comment by rbarreiro** [comment]
done in idris repo
